Config is now initialized and passed through main.ts
Deno-Synthesis/Synthesis pull request #11
Opened 2021-09-16 14:57 UTC by DebitCardz

2021-09-16 14:58 UTC, DebitCardz commented
Also added `DiscordConfigSection` and `GithubConfigSection` so when the time comes we can just pass those for wherever we need.

2021-09-16 15:00 UTC, CoreyShupe requested changes

2021-09-16 15:00 UTC, CoreyShupe commented on src/types/Config.ts
> +  discord: DiscordConfigSection;
Can we rename this and the github one to `DiscordConfiguration` and `GithubConfiguration`

2021-09-16 15:00 UTC, DebitCardz commented on src/types/Config.ts
> +  discord: DiscordConfigSection;
Yeah sure, the inner Spigot developer in me just told me to name it Section.

2021-09-16 15:03 UTC, DebitCardz commented
Hold on integration/github.ts is throwing an error because of `Uncaught ReferenceError: Cannot access 'config' before initialization`

2021-09-17 00:07 UTC, CoreyShupe commented
This should be handled better via #12

2021-09-17 00:07 UTC, closed without merging