Moved Github integration into a class
Deno-Synthesis/Synthesis pull request #14
Opened 2021-09-16 19:00 UTC by DebitCardz

Added it to SynthesisClient

2021-09-16 21:49 UTC, DebitCardz commented
It may be possible for integration#resync to return a JSON object with data such as

- Issues channel
- Total comments
- Total issues/prs
For now it'll just return the new issues channel so we can save that somewhere(SynthesisClient?).

2021-09-17 00:06 UTC, CoreyShupe requested changes

2021-09-17 00:06 UTC, CoreyShupe commented on src/client.ts
> +  public github: GithubIntegration;
make this readonly private along with a getter, and remove the line between config and github

2021-09-17 00:06 UTC, CoreyShupe commented on src/commands/SyncCommand.ts
> +    const client = ctx.client as SynthesisClient;
this should be handled in functions for proper assertion of the SynthesisClient

2021-09-17 00:06 UTC, CoreyShupe commented on src/commands/SyncCommand.ts
> +    await client.github.resync(config, ctx.guild);
github integration should solely be a linker between TS and Github, it should not supply logic

2021-09-17 00:06 UTC, CoreyShupe commented on src/github/integration.ts
> +import Config, { config } from "../types/Config.ts";
remove the `config` decleration here

2021-09-17 00:06 UTC, CoreyShupe commented on src/github/integration.ts
> +  async resync(config: Config, guild: Guild): Promise<GuildChannel> {
again, this class should not be handling logic of issues, it should merely be an interface to github

2021-09-17 00:06 UTC, CoreyShupe commented on src/github/integration.ts
> +  private async generateIssuesChannel(
this shouldn't be handled by github integration

2021-09-17 00:06 UTC, CoreyShupe commented on src/util/functions.ts
>  export const requireSynthesisConfig = (ctx: CommandContext): Config =>
we should also have something which returns the SynthesisClient or properly throws in this file

2021-09-17 00:13 UTC, DebitCardz commented on src/client.ts
> +  public github: GithubIntegration;
We can make this a public readonly instead.

2021-09-19 16:55 UTC, CoreyShupe requested changes

2021-09-19 16:55 UTC, CoreyShupe commented on src/client.ts
> +  async ready() {
why did we remove the explicit `:void` and why does this need to be async

2021-09-19 16:55 UTC, CoreyShupe commented on src/commands/SyncCommand.ts
> +    const information = await this.resync(client.github, config, ctx.guild);
why don't we just pass client into this and get `client.github` and `client.config`

2021-09-19 16:55 UTC, CoreyShupe commented on src/commands/SyncCommand.ts
> +    const client = issuesChannel.client;
this seems like a messy way to get the client, just pass the client in

2021-09-19 16:56 UTC, DebitCardz commented on src/client.ts
> +  async ready() {
This was an old change I made when testing something that I forgot to revert.

2021-09-19 16:57 UTC, DebitCardz commented on src/commands/SyncCommand.ts
> +    const information = await this.resync(client.github, config, ctx.guild);
I felt like it'd just be cleaner to only pass exactly whatever we needed, we don't need the entire client scope so I only passed the things we needed.
Let me know if you'd like this changed.

2021-09-19 17:02 UTC, DebitCardz commented on src/commands/SyncCommand.ts
> +    const information = await this.resync(client.github, config, ctx.guild);
Actually this has been changed in the latest commit to just pass client.

2021-09-19 17:02 UTC, DebitCardz commented on src/commands/SyncCommand.ts
> +    const client = issuesChannel.client;
Yeah agreed, fixed this.

2021-09-20 01:41 UTC, CoreyShupe commented
LGTM

2021-09-20 01:41 UTC, merged

2021-09-20 01:42 UTC, DebitCardz commented
WGTM